services:
  timescaledb:
    image: timescale/timescaledb-ha:pg18
    container_name: timescaledb
    restart: unless-stopped
    environment:
      PGDATA: /pgdata
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./timescaledb:/pgdata

  mosquitto:
    image: eclipse-mosquitto:2.1.2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"    # MQTT
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
